### ISSUE TITLE
400 Bad Request Error

### ISSUE THREAD

**Issue by Meghdeep** [rhayun/python-youtube-api#2]
I'm getting a 400 bad request for pretty much every function here.

urllib2.HTTPError: HTTP Error 400: Bad Request

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "youtubeapi.py", line 50, in get_video_info
    apiData = self.api_get(api_url, params)
  File "youtubeapi.py", line 281, in api_get
    f = urllib2.urlopen(url + "?" + urllib.urlencode(params))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by rhayun** [comment]
Sorry but this project is not maintained more - contribution to the project is welcome
